project:
  type: website

website:
  repo-url: https://github.com/data-and-visualization/Intro2R
  repo-actions: [edit, issue]
  page-footer:  "Text and figures are licensed under Creative Commons Attribution
  [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)<br>
  [Rfun](https://rfun.library.duke.edu) · 
  [Center for Data & Visualization Sciences](https://library.duke.edu/data) · 
  [Duke University Libraries](https://library.duke.edu)"
  title: "Intro to R (Rfun)"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - data_management.qmd
      - data_wrangling.qmd
      - visualization.qmd
      - gis.qmd
      - version_control.qmd
      - text: "More Rfun!"
        href: "https://Rfun.library.duke.edu"
      - about.qmd
    right:
      - icon: github
        href: https://github.com/data-and-visualization/Intro2R
        aria-label: GitHub
      # - icon: home
      - text: Rfun|CDVS
        menu:
          - text: "Rfun Home"
            href: "https://rfun.library.duke.edu/"
          - text: "Center for Data & Visualization"
            href: https://library.duke.edu/data/

format:
  html:
    page-layout: full
    theme: flatly
    css: styles.css
    toc: true
    # include-after-body: _footer.html

editor: visual

